title: Boyomi's Blog
email: boyunqueen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "boyunjjang1.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: BoYun Kang # add your name
author-pic: boyun-face.JPG
about-author: My name is BoYun Kang. I'm a graduate of Korea Game Science High School 11th. a student of Computer Engineering at Inha University.

# Contact links
email: boyunqueen@gmail.com
phone: 010-9779-2514
website: boyunjjang1.github.io # Add your website, do not add http://
github: boyunjjang1 # Add your Github handle
twitter: boyunjjang1 # Add your Twitter handle
facebook: profile.php?id=100004937532760 # Add your Facebook handle
instagram: bo_yoonvely # Add your Instagram handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: Boyomi # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
